export const vocab = {
  Basics: [
    { id: 1, english: "Hello", spanish: "Hola", learned: false },
    { id: 2, english: "Goodbye", spanish: "Adiós", learned: false },
    { id: 3, english: "Please", spanish: "Por favor", learned: false },
    { id: 4, english: "Thank you", spanish: "Gracias", learned: false },
    { id: 5, english: "You're welcome", spanish: "De nada", learned: false },
    { id: 6, english: "Excuse me", spanish: "Perdón", learned: false },
    { id: 7, english: "I'm sorry", spanish: "Lo siento", learned: false },
  ],
  Introductions: [
    { id: 8, english: "My name is", spanish: "Me llamo", learned: false },
    {
      id: 9,
      english: "What is your name?",
      spanish: "¿Cómo te llamas?",
      learned: false,
    },
    {
      id: 10,
      english: "Nice to meet you",
      spanish: "Encantado/a",
      learned: false,
    },
    {
      id: 11,
      english: "How are you?",
      spanish: "¿Cómo estás?",
      learned: false,
    },
    { id: 12, english: "I am fine", spanish: "Estoy bien", learned: false },
    { id: 13, english: "And you?", spanish: "¿Y tú?", learned: false },
    {
      id: 14,
      english: "Where are you from?",
      spanish: "¿De dónde eres?",
      learned: false,
    },
    { id: 15, english: "I am from", spanish: "Soy de", learned: false },
  ],
  "Numbers and Time": [
    { id: 26, english: "One", spanish: "Uno", learned: false },
    { id: 27, english: "Two", spanish: "Dos", learned: false },
    { id: 28, english: "Three", spanish: "Tres", learned: false },
    { id: 29, english: "Four", spanish: "Cuatro", learned: false },
    { id: 30, english: "Five", spanish: "Cinco", learned: false },
    { id: 31, english: "Today", spanish: "Hoy", learned: false },
    { id: 32, english: "Tomorrow", spanish: "Mañana", learned: false },
    { id: 33, english: "Yesterday", spanish: "Ayer", learned: false },
    { id: 34, english: "Week", spanish: "Semana", learned: false },
    { id: 35, english: "Month", spanish: "Mes", learned: false },
    { id: 36, english: "Year", spanish: "Año", learned: false },
  ],
  "Daily Activities": [
    { id: 37, english: "To eat", spanish: "Comer" },
    { id: 38, english: "To drink", spanish: "Beber" },
    { id: 39, english: "To sleep", spanish: "Dormir" },
    { id: 40, english: "To work", spanish: "Trabajar" },
    { id: 41, english: "To study", spanish: "Estudiar" },
    { id: 42, english: "To walk", spanish: "Caminar" },
    { id: 43, english: "To run", spanish: "Correr" },
    { id: 44, english: "To cook", spanish: "Cocinar" },
    { id: 45, english: "To read", spanish: "Leer" },
    { id: 46, english: "To write", spanish: "Escribir" },
    { id: 47, english: "To watch", spanish: "Mirar" },
    { id: 48, english: "To listen", spanish: "Escuchar" },
    { id: 49, english: "To speak", spanish: "Hablar" },
    { id: 50, english: "To clean", spanish: "Limpiar" },
    { id: 51, english: "To shower", spanish: "Ducharse" },
    { id: 52, english: "To get up", spanish: "Levantarse" },
    { id: 53, english: "To brush (teeth)", spanish: "Cepillarse los dientes" },
    { id: 54, english: "To dress", spanish: "Vestirse" },
    { id: 55, english: "To undress", spanish: "Desvestirse" },
    { id: 56, english: "To comb (hair)", spanish: "Peinarse" },
    { id: 57, english: "To exercise", spanish: "Hacer ejercicio" },
    { id: 58, english: "To relax", spanish: "Relajarse" },
    { id: 59, english: "To wake up", spanish: "Despertarse" },
    { id: 60, english: "To take a nap", spanish: "Echar una siesta" },
    { id: 61, english: "To go to bed", spanish: "Acostarse" },
    { id: 62, english: "To tidy up", spanish: "Ordenar" },
    { id: 63, english: "To shop", spanish: "Hacer compras" },
    { id: 64, english: "To spend time", spanish: "Pasar tiempo" },
    { id: 65, english: "To enjoy", spanish: "Disfrutar" },
    { id: 66, english: "To call (someone)", spanish: "Llamar" },
    { id: 67, english: "To pay", spanish: "Pagar" },
    { id: 68, english: "To help", spanish: "Ayudar" },
    { id: 69, english: "To open", spanish: "Abrir" },
    { id: 70, english: "To close", spanish: "Cerrar" },
    { id: 71, english: "To stretch", spanish: "Estirarse" },
    { id: 72, english: "To meditate", spanish: "Meditar" },
    { id: 73, english: "To pack", spanish: "Empacar" },
    { id: 74, english: "To unpack", spanish: "Desempacar" },
    { id: 75, english: "To drive", spanish: "Conducir" },
    { id: 76, english: "To park", spanish: "Estacionar" },
    { id: 77, english: "To make the bed", spanish: "Hacer la cama" },
    { id: 78, english: "To water the plants", spanish: "Regar las plantas" },
    { id: 79, english: "To take out the trash", spanish: "Sacar la basura" },
    { id: 80, english: "To vacuum", spanish: "Pasar la aspiradora" },
    { id: 81, english: "To iron clothes", spanish: "Planchar la ropa" },
    { id: 82, english: "To wash dishes", spanish: "Lavar los platos" },
    { id: 83, english: "To wash clothes", spanish: "Lavar la ropa" },
    { id: 84, english: "To fold clothes", spanish: "Doblar la ropa" },
    { id: 85, english: "To sweep", spanish: "Barrer" },
    { id: 86, english: "To mop", spanish: "Trapear" },
    { id: 87, english: "To rest", spanish: "Descansar" },
    { id: 88, english: "To call someone", spanish: "Hacer una llamada" },
    {
      id: 89,
      english: "To check email",
      spanish: "Revisar el correo electrónico",
    },
    { id: 90, english: "To send a message", spanish: "Enviar un mensaje" },
    { id: 91, english: "To charge the phone", spanish: "Cargar el teléfono" },
    { id: 92, english: "To feed the pet", spanish: "Alimentar a la mascota" },
    { id: 93, english: "To go shopping", spanish: "Ir de compras" },
    { id: 94, english: "To pay bills", spanish: "Pagar las cuentas" },
    { id: 95, english: "To do homework", spanish: "Hacer la tarea" },
    { id: 96, english: "To plan the day", spanish: "Planear el día" },
    { id: 97, english: "To organize", spanish: "Organizar" },
    { id: 98, english: "To garden", spanish: "Jardinear" },
    { id: 99, english: "To commute", spanish: "Desplazarse" },
    { id: 100, english: "To greet someone", spanish: "Saludar a alguien" },
    { id: 101, english: "To say goodbye", spanish: "Despedirse" },
    { id: 102, english: "To set an alarm", spanish: "Poner una alarma" },
    { id: 103, english: "To turn on the light", spanish: "Encender la luz" },
    { id: 104, english: "To turn off the light", spanish: "Apagar la luz" },
    { id: 105, english: "To prepare a meal", spanish: "Preparar una comida" },
    { id: 106, english: "To eat breakfast", spanish: "Desayunar" },
    { id: 107, english: "To eat lunch", spanish: "Almorzar" },
    { id: 108, english: "To eat dinner", spanish: "Cenar" },
    { id: 109, english: "To boil water", spanish: "Hervir agua" },
  ],
  "Directions and Travel": [
    { id: 110, english: "Right", spanish: "Derecha" },
    { id: 111, english: "Left", spanish: "Izquierda" },
    { id: 112, english: "Straight ahead", spanish: "Todo recto" },
    { id: 113, english: "Near", spanish: "Cerca" },
    { id: 114, english: "Far", spanish: "Lejos" },
    { id: 115, english: "To turn", spanish: "Girar" },
    { id: 116, english: "To stop", spanish: "Parar" },
    { id: 117, english: "Where is...", spanish: "¿Dónde está...?" },
    { id: 118, english: "The station", spanish: "La estación" },
    { id: 119, english: "The airport", spanish: "El aeropuerto" },
    { id: 120, english: "The hotel", spanish: "El hotel" },
    { id: 121, english: "The restaurant", spanish: "El restaurante" },
    { id: 122, english: "The bus stop", spanish: "La parada de autobús" },
    { id: 123, english: "The train", spanish: "El tren" },
    { id: 124, english: "The taxi", spanish: "El taxi" },
    { id: 125, english: "The car", spanish: "El coche" },
    { id: 126, english: "To travel", spanish: "Viajar" },
    { id: 127, english: "The map", spanish: "El mapa" },
    { id: 128, english: "To fly", spanish: "Volar" },
    { id: 129, english: "The ticket", spanish: "El boleto" },
    { id: 130, english: "Passport", spanish: "Pasaporte" },
    { id: 131, english: "Customs", spanish: "Aduana" },
    { id: 132, english: "Luggage", spanish: "Equipaje" },
    { id: 133, english: "Arrival", spanish: "Llegada" },
    { id: 134, english: "Departure", spanish: "Salida" },
    { id: 135, english: "Road", spanish: "Carretera" },
    { id: 136, english: "Bridge", spanish: "Puente" },
    { id: 137, english: "Traffic light", spanish: "Semáforo" },
    { id: 138, english: "To cross", spanish: "Cruzar" },
    { id: 139, english: "Highway", spanish: "Autopista" },
    { id: 140, english: "Intersection", spanish: "Intersección" },
    { id: 141, english: "Pedestrian", spanish: "Peatón" },
    { id: 142, english: "Parking", spanish: "Estacionamiento" },
    { id: 143, english: "To book (a room, ticket)", spanish: "Reservar" },
    { id: 144, english: "To check in", spanish: "Registrarse" },
    { id: 145, english: "To check out", spanish: "Hacer el check-out" },
    { id: 146, english: "Travel insurance", spanish: "Seguro de viaje" },
    { id: 147, english: "Travel guide", spanish: "Guía de viaje" },
  ],
  "Food and Drink": [
    { id: 148, english: "Water", spanish: "Agua" },
    { id: 149, english: "Bread", spanish: "Pan" },
    { id: 150, english: "Milk", spanish: "Leche" },
    { id: 151, english: "Coffee", spanish: "Café" },
    { id: 152, english: "Tea", spanish: "Té" },
    { id: 153, english: "Juice", spanish: "Jugo" },
    { id: 154, english: "Wine", spanish: "Vino" },
    { id: 155, english: "Beer", spanish: "Cerveza" },
    { id: 156, english: "Cheese", spanish: "Queso" },
    { id: 157, english: "Butter", spanish: "Mantequilla" },
    { id: 158, english: "Eggs", spanish: "Huevos" },
    { id: 159, english: "Rice", spanish: "Arroz" },
    { id: 160, english: "Meat", spanish: "Carne" },
    { id: 161, english: "Fish", spanish: "Pescado" },
    { id: 162, english: "Chicken", spanish: "Pollo" },
    { id: 163, english: "Vegetables", spanish: "Verduras" },
    { id: 164, english: "Fruit", spanish: "Fruta" },
    { id: 165, english: "Apple", spanish: "Manzana" },
    { id: 166, english: "Orange", spanish: "Naranja" },
    { id: 167, english: "Banana", spanish: "Plátano" },
    { id: 168, english: "Grapes", spanish: "Uvas" },
    { id: 169, english: "Tomato", spanish: "Tomate" },
    { id: 170, english: "Potato", spanish: "Papa" },
    { id: 171, english: "Onion", spanish: "Cebolla" },
    { id: 172, english: "Salt", spanish: "Sal" },
    { id: 173, english: "Pepper", spanish: "Pimienta" },
    { id: 174, english: "Sugar", spanish: "Azúcar" },
    { id: 175, english: "Soup", spanish: "Sopa" },
    { id: 176, english: "Salad", spanish: "Ensalada" },
    { id: 177, english: "Breakfast", spanish: "Desayuno" },
    { id: 178, english: "Lunch", spanish: "Almuerzo" },
    { id: 179, english: "Dinner", spanish: "Cena" },
    { id: 180, english: "Dessert", spanish: "Postre" },
    { id: 181, english: "Ice cream", spanish: "Helado" },
    { id: 182, english: "Cake", spanish: "Pastel" },
    { id: 183, english: "Snack", spanish: "Bocadillo" },
    { id: 184, english: "To eat", spanish: "Comer" },
    { id: 185, english: "To drink", spanish: "Beber" },
    { id: 186, english: "Menu", spanish: "Menú" },
    { id: 187, english: "Fork", spanish: "Tenedor" },
    { id: 188, english: "Knife", spanish: "Cuchillo" },
    { id: 189, english: "Spoon", spanish: "Cuchara" },
    { id: 190, english: "Plate", spanish: "Plato" },
    { id: 191, english: "Cup", spanish: "Taza" },
    { id: 192, english: "Napkin", spanish: "Servilleta" },
    { id: 193, english: "Bill", spanish: "Cuenta" },
    { id: 194, english: "Waiter", spanish: "Camarero" },
    { id: 195, english: "To order", spanish: "Pedir" },
    { id: 196, english: "Delicious", spanish: "Delicioso" },
  ],
  Shopping: [
    { id: 197, english: "Shop", spanish: "Tienda" },
    { id: 198, english: "Market", spanish: "Mercado" },
    { id: 199, english: "Supermarket", spanish: "Supermercado" },
    { id: 200, english: "Mall", spanish: "Centro comercial" },
    { id: 201, english: "Price", spanish: "Precio" },
    { id: 202, english: "Discount", spanish: "Descuento" },
    { id: 203, english: "Sale", spanish: "Venta" },
    { id: 204, english: "Cash", spanish: "Efectivo" },
    { id: 205, english: "Credit card", spanish: "Tarjeta de crédito" },
    { id: 206, english: "Receipt", spanish: "Recibo" },
    { id: 207, english: "Bag", spanish: "Bolsa" },
    { id: 208, english: "To buy", spanish: "Comprar" },
    { id: 209, english: "To sell", spanish: "Vender" },
    { id: 210, english: "To pay", spanish: "Pagar" },
    { id: 211, english: "To return", spanish: "Devolver" },
    { id: 212, english: "To try on", spanish: "Probarse" },
    { id: 213, english: "Size", spanish: "Talla" },
    { id: 214, english: "Small", spanish: "Pequeño" },
    { id: 215, english: "Medium", spanish: "Mediano" },
    { id: 216, english: "Large", spanish: "Grande" },
    { id: 217, english: "Expensive", spanish: "Caro" },
    { id: 218, english: "Cheap", spanish: "Barato" },
    { id: 219, english: "Product", spanish: "Producto" },
    { id: 220, english: "Customer", spanish: "Cliente" },
    { id: 221, english: "Seller", spanish: "Vendedor" },
    { id: 222, english: "Department", spanish: "Departamento" },
    { id: 223, english: "Jewelry", spanish: "Joyería" },
    { id: 224, english: "Clothing", spanish: "Ropa" },
    { id: 225, english: "Shoes", spanish: "Zapatos" },
    { id: 226, english: "Accessories", spanish: "Accesorios" },
    { id: 227, english: "Furniture", spanish: "Muebles" },
    { id: 228, english: "Groceries", spanish: "Comestibles" },
    { id: 229, english: "To look for", spanish: "Buscar" },
    { id: 230, english: "Shelf", spanish: "Estante" },
    { id: 231, english: "Basket", spanish: "Canasta" },
    { id: 232, english: "Cart", spanish: "Carrito" },
    { id: 233, english: "To exchange", spanish: "Cambiar" },
    { id: 234, english: "Currency", spanish: "Moneda" },
    { id: 235, english: "Cashier", spanish: "Cajero" },
    { id: 236, english: "Line (queue)", spanish: "Fila" },
    { id: 237, english: "Store hours", spanish: "Horario de la tienda" },
    { id: 238, english: "Open", spanish: "Abierto" },
    { id: 239, english: "Closed", spanish: "Cerrado" },
  ],
  "Feelings and Descriptions": [
    { id: 240, english: "Happy", spanish: "Feliz" },
    { id: 241, english: "Sad", spanish: "Triste" },
    { id: 242, english: "Angry", spanish: "Enojado/a" },
    { id: 243, english: "Excited", spanish: "Emocionado/a" },
    { id: 244, english: "Tired", spanish: "Cansado/a" },
    { id: 245, english: "Scared", spanish: "Asustado/a" },
    { id: 246, english: "Calm", spanish: "Calmado/a" },
    { id: 247, english: "Nervous", spanish: "Nervioso/a" },
    { id: 248, english: "Surprised", spanish: "Sorprendido/a" },
    { id: 249, english: "Confident", spanish: "Seguro/a" },
    { id: 250, english: "Bored", spanish: "Aburrido/a" },
    { id: 251, english: "Embarrassed", spanish: "Avergonzado/a" },
    { id: 252, english: "Cold", spanish: "Frío/a" },
    { id: 253, english: "Hot", spanish: "Caliente" },
    { id: 254, english: "Hungry", spanish: "Hambriento/a" },
    { id: 255, english: "Thirsty", spanish: "Sediento/a" },
    { id: 256, english: "Healthy", spanish: "Saludable" },
    { id: 257, english: "Sick", spanish: "Enfermo/a" },
    { id: 258, english: "Beautiful", spanish: "Hermoso/a" },
    { id: 259, english: "Ugly", spanish: "Feo/a" },
    { id: 260, english: "Big", spanish: "Grande" },
    { id: 261, english: "Small", spanish: "Pequeño/a" },
    { id: 262, english: "Tall", spanish: "Alto/a" },
    { id: 263, english: "Short", spanish: "Bajo/a" },
    { id: 264, english: "Fast", spanish: "Rápido/a" },
    { id: 265, english: "Slow", spanish: "Lento/a" },
    { id: 266, english: "Strong", spanish: "Fuerte" },
    { id: 267, english: "Weak", spanish: "Débil" },
    { id: 268, english: "Clean", spanish: "Limpio/a" },
    { id: 269, english: "Dirty", spanish: "Sucio/a" },
    { id: 270, english: "Expensive", spanish: "Caro/a" },
    { id: 271, english: "Cheap", spanish: "Barato/a" },
    { id: 272, english: "New", spanish: "Nuevo/a" },
    { id: 273, english: "Old", spanish: "Viejo/a" },
    { id: 274, english: "Open", spanish: "Abierto/a" },
    { id: 275, english: "Closed", spanish: "Cerrado/a" },
    { id: 276, english: "Interesting", spanish: "Interesante" },
    { id: 277, english: "Fun", spanish: "Divertido/a" },
    { id: 278, english: "Serious", spanish: "Serio/a" },
    { id: 279, english: "Easy", spanish: "Fácil" },
    { id: 280, english: "Difficult", spanish: "Difícil" },
  ],
  "Colors and Shapes": [
    { id: 281, english: "Red", spanish: "Rojo/a" },
    { id: 282, english: "Blue", spanish: "Azul" },
    { id: 283, english: "Green", spanish: "Verde" },
    { id: 284, english: "Yellow", spanish: "Amarillo/a" },
    { id: 285, english: "Orange", spanish: "Naranja" },
    { id: 286, english: "Purple", spanish: "Morado/a" },
    { id: 287, english: "Pink", spanish: "Rosa" },
    { id: 288, english: "Brown", spanish: "Marrón" },
    { id: 289, english: "Black", spanish: "Negro/a" },
    { id: 290, english: "White", spanish: "Blanco/a" },
    { id: 291, english: "Gray", spanish: "Gris" },
    { id: 292, english: "Light", spanish: "Claro/a" },
    { id: 293, english: "Dark", spanish: "Oscuro/a" },
    { id: 294, english: "Bright", spanish: "Brillante" },
    { id: 295, english: "Square", spanish: "Cuadrado/a" },
    { id: 296, english: "Circle", spanish: "Círculo" },
    { id: 297, english: "Triangle", spanish: "Triángulo" },
    { id: 298, english: "Rectangle", spanish: "Rectángulo" },
    { id: 299, english: "Oval", spanish: "Óvalo" },
    { id: 300, english: "Star", spanish: "Estrella" },
    { id: 301, english: "Diamond", spanish: "Diamante" },
    { id: 302, english: "Heart", spanish: "Corazón" },
    { id: 303, english: "Hexagon", spanish: "Hexágono" },
    { id: 304, english: "Pentagon", spanish: "Pentágono" },
    { id: 305, english: "Cube", spanish: "Cubo" },
    { id: 306, english: "Sphere", spanish: "Esfera" },
    { id: 307, english: "Pyramid", spanish: "Pirámide" },
    { id: 308, english: "Cone", spanish: "Cono" },
    { id: 309, english: "Cylinder", spanish: "Cilindro" },
    { id: 310, english: "Line", spanish: "Línea" },
    { id: 311, english: "Point", spanish: "Punto" },
  ],
  "Common Verbs": [
    { id: 312, english: "To be (permanent)", spanish: "Ser" },
    { id: 313, english: "To be (temporary)", spanish: "Estar" },
    { id: 314, english: "To have", spanish: "Tener" },
    { id: 315, english: "To do", spanish: "Hacer" },
    { id: 316, english: "To go", spanish: "Ir" },
    { id: 317, english: "To see", spanish: "Ver" },
    { id: 318, english: "To say", spanish: "Decir" },
    { id: 319, english: "To speak", spanish: "Hablar" },
    { id: 320, english: "To hear", spanish: "Oír" },
    { id: 321, english: "To listen", spanish: "Escuchar" },
    { id: 322, english: "To read", spanish: "Leer" },
    { id: 323, english: "To write", spanish: "Escribir" },
    { id: 324, english: "To eat", spanish: "Comer" },
    { id: 325, english: "To drink", spanish: "Beber" },
    { id: 326, english: "To sleep", spanish: "Dormir" },
    { id: 327, english: "To wake up", spanish: "Despertarse" },
    { id: 328, english: "To work", spanish: "Trabajar" },
    { id: 329, english: "To study", spanish: "Estudiar" },
    { id: 330, english: "To play", spanish: "Jugar" },
    { id: 331, english: "To run", spanish: "Correr" },
    { id: 332, english: "To walk", spanish: "Caminar" },
    { id: 333, english: "To take", spanish: "Tomar" },
    { id: 334, english: "To give", spanish: "Dar" },
    { id: 335, english: "To open", spanish: "Abrir" },
    { id: 336, english: "To close", spanish: "Cerrar" },
    { id: 337, english: "To think", spanish: "Pensar" },
    { id: 338, english: "To know (a fact)", spanish: "Saber" },
    { id: 339, english: "To know (someone)", spanish: "Conocer" },
    { id: 340, english: "To understand", spanish: "Entender" },
    { id: 341, english: "To learn", spanish: "Aprender" },
    { id: 342, english: "To teach", spanish: "Enseñar" },
    { id: 343, english: "To drive", spanish: "Conducir" },
    { id: 344, english: "To wait", spanish: "Esperar" },
    { id: 345, english: "To call", spanish: "Llamar" },
    { id: 346, english: "To love", spanish: "Amar" },
    { id: 347, english: "To like", spanish: "Gustar" },
    { id: 348, english: "To help", spanish: "Ayudar" },
    { id: 349, english: "To clean", spanish: "Limpiar" },
    { id: 350, english: "To wash", spanish: "Lavar" },
    { id: 351, english: "To look for", spanish: "Buscar" },
    { id: 352, english: "To find", spanish: "Encontrar" },
    { id: 353, english: "To bring", spanish: "Traer" },
    { id: 354, english: "To carry", spanish: "Llevar" },
    { id: 355, english: "To put", spanish: "Poner" },
    { id: 356, english: "To leave", spanish: "Salir" },
    { id: 357, english: "To return", spanish: "Volver" },
    { id: 358, english: "To enter", spanish: "Entrar" },
    { id: 359, english: "To live", spanish: "Vivir" },
    { id: 360, english: "To die", spanish: "Morir" },
  ],
  "Everyday Objects": [
    { id: 361, english: "Table", spanish: "Mesa" },
    { id: 362, english: "Chair", spanish: "Silla" },
    { id: 363, english: "Bed", spanish: "Cama" },
    { id: 364, english: "Sofa", spanish: "Sofá" },
    { id: 365, english: "Lamp", spanish: "Lámpara" },
    { id: 366, english: "Light bulb", spanish: "Bombilla" },
    { id: 367, english: "Television", spanish: "Televisión" },
    { id: 368, english: "Remote control", spanish: "Control remoto" },
    { id: 369, english: "Phone", spanish: "Teléfono" },
    { id: 370, english: "Computer", spanish: "Computadora" },
    { id: 371, english: "Tablet", spanish: "Tableta" },
    { id: 372, english: "Pen", spanish: "Bolígrafo" },
    { id: 373, english: "Pencil", spanish: "Lápiz" },
    { id: 374, english: "Notebook", spanish: "Cuaderno" },
    { id: 375, english: "Book", spanish: "Libro" },
    { id: 376, english: "Clock", spanish: "Reloj" },
    { id: 377, english: "Watch", spanish: "Reloj de pulsera" },
    { id: 378, english: "Backpack", spanish: "Mochila" },
    { id: 379, english: "Wallet", spanish: "Cartera" },
    { id: 380, english: "Bag", spanish: "Bolsa" },
    { id: 381, english: "Key", spanish: "Llave" },
    { id: 382, english: "Door", spanish: "Puerta" },
    { id: 383, english: "Window", spanish: "Ventana" },
    { id: 384, english: "Mirror", spanish: "Espejo" },
    { id: 385, english: "Carpet", spanish: "Alfombra" },
    { id: 386, english: "Curtains", spanish: "Cortinas" },
    { id: 387, english: "Fan", spanish: "Ventilador" },
    { id: 388, english: "Air conditioner", spanish: "Aire acondicionado" },
    { id: 389, english: "Heater", spanish: "Calefactor" },
    { id: 390, english: "Stove", spanish: "Estufa" },
    { id: 391, english: "Refrigerator", spanish: "Refrigerador" },
    { id: 392, english: "Microwave", spanish: "Microondas" },
    { id: 393, english: "Oven", spanish: "Horno" },
    { id: 394, english: "Plate", spanish: "Plato" },
    { id: 395, english: "Glass", spanish: "Vaso" },
    { id: 396, english: "Cup", spanish: "Taza" },
    { id: 397, english: "Fork", spanish: "Tenedor" },
    { id: 398, english: "Knife", spanish: "Cuchillo" },
    { id: 399, english: "Spoon", spanish: "Cuchara" },
    { id: 400, english: "Trash can", spanish: "Basurero" },
    { id: 401, english: "Broom", spanish: "Escoba" },
    { id: 402, english: "Mop", spanish: "Trapeador" },
    { id: 403, english: "Laundry basket", spanish: "Cesto de ropa" },
    { id: 404, english: "Iron", spanish: "Plancha" },
    { id: 405, english: "Vacuum cleaner", spanish: "Aspiradora" },
  ],
  "Body Parts": [
    { id: 406, english: "Head", spanish: "Cabeza" },
    { id: 407, english: "Hair", spanish: "Pelo" },
    { id: 408, english: "Face", spanish: "Cara" },
    { id: 409, english: "Forehead", spanish: "Frente" },
    { id: 410, english: "Eyes", spanish: "Ojos" },
    { id: 411, english: "Ears", spanish: "Orejas" },
    { id: 412, english: "Nose", spanish: "Nariz" },
    { id: 413, english: "Mouth", spanish: "Boca" },
    { id: 414, english: "Teeth", spanish: "Dientes" },
    { id: 415, english: "Lips", spanish: "Labios" },
    { id: 416, english: "Tongue", spanish: "Lengua" },
    { id: 417, english: "Neck", spanish: "Cuello" },
    { id: 418, english: "Shoulder", spanish: "Hombro" },
    { id: 419, english: "Arm", spanish: "Brazo" },
    { id: 420, english: "Elbow", spanish: "Codo" },
    { id: 421, english: "Hand", spanish: "Mano" },
    { id: 422, english: "Fingers", spanish: "Dedos" },
    { id: 423, english: "Chest", spanish: "Pecho" },
    { id: 424, english: "Back", spanish: "Espalda" },
    { id: 425, english: "Stomach", spanish: "Estómago" },
    { id: 426, english: "Waist", spanish: "Cintura" },
    { id: 427, english: "Hip", spanish: "Cadera" },
    { id: 428, english: "Leg", spanish: "Pierna" },
    { id: 429, english: "Knee", spanish: "Rodilla" },
    { id: 430, english: "Foot", spanish: "Pie" },
    { id: 431, english: "Toes", spanish: "Dedos del pie" },
    { id: 432, english: "Skin", spanish: "Piel" },
    { id: 433, english: "Bone", spanish: "Hueso" },
    { id: 434, english: "Muscle", spanish: "Músculo" },
    { id: 435, english: "Heart", spanish: "Corazón" },
    { id: 436, english: "Lung", spanish: "Pulmón" },
    { id: 437, english: "Brain", spanish: "Cerebro" },
    { id: 438, english: "Liver", spanish: "Hígado" },
    { id: 439, english: "Nail", spanish: "Uña" },
    { id: 440, english: "Throat", spanish: "Garganta" },
    { id: 441, english: "Ankle", spanish: "Tobillo" },
    { id: 442, english: "Wrist", spanish: "Muñeca" },
    { id: 443, english: "Cheek", spanish: "Mejilla" },
    { id: 444, english: "Chin", spanish: "Barbilla" },
  ],
  "Nature and Weather": [
    { id: 445, english: "Sun", spanish: "Sol" },
    { id: 446, english: "Moon", spanish: "Luna" },
    { id: 447, english: "Star", spanish: "Estrella" },
    { id: 448, english: "Sky", spanish: "Cielo" },
    { id: 449, english: "Cloud", spanish: "Nube" },
    { id: 450, english: "Rain", spanish: "Lluvia" },
    { id: 451, english: "Snow", spanish: "Nieve" },
    { id: 452, english: "Wind", spanish: "Viento" },
    { id: 453, english: "Storm", spanish: "Tormenta" },
    { id: 454, english: "Lightning", spanish: "Relámpago" },
    { id: 455, english: "Thunder", spanish: "Trueno" },
    { id: 456, english: "Rainbow", spanish: "Arcoíris" },
    { id: 457, english: "Tree", spanish: "Árbol" },
    { id: 458, english: "Flower", spanish: "Flor" },
    { id: 459, english: "Grass", spanish: "Hierba" },
    { id: 460, english: "Leaf", spanish: "Hoja" },
    { id: 461, english: "Forest", spanish: "Bosque" },
    { id: 462, english: "Mountain", spanish: "Montaña" },
    { id: 463, english: "River", spanish: "Río" },
    { id: 464, english: "Lake", spanish: "Lago" },
    { id: 465, english: "Sea", spanish: "Mar" },
    { id: 466, english: "Ocean", spanish: "Océano" },
    { id: 467, english: "Beach", spanish: "Playa" },
    { id: 468, english: "Sand", spanish: "Arena" },
    { id: 469, english: "Rock", spanish: "Roca" },
    { id: 470, english: "Cave", spanish: "Cueva" },
    { id: 471, english: "Desert", spanish: "Desierto" },
    { id: 472, english: "Island", spanish: "Isla" },
    { id: 473, english: "Volcano", spanish: "Volcán" },
    { id: 474, english: "Earthquake", spanish: "Terremoto" },
    { id: 475, english: "Fire", spanish: "Fuego" },
    { id: 476, english: "Ice", spanish: "Hielo" },
    { id: 477, english: "Fog", spanish: "Niebla" },
    { id: 478, english: "Hurricane", spanish: "Huracán" },
    { id: 479, english: "Wave", spanish: "Ola" },
    { id: 480, english: "Temperature", spanish: "Temperatura" },
    { id: 481, english: "Hot", spanish: "Calor" },
    { id: 482, english: "Cold", spanish: "Frío" },
    { id: 483, english: "Spring", spanish: "Primavera" },
    { id: 484, english: "Summer", spanish: "Verano" },
    { id: 485, english: "Autumn", spanish: "Otoño" },
    { id: 486, english: "Winter", spanish: "Invierno" },
  ],
  "Technology and Modern Life": [
    { id: 487, english: "Computer", spanish: "Computadora" },
    { id: 488, english: "Laptop", spanish: "Portátil" },
    { id: 489, english: "Tablet", spanish: "Tableta" },
    { id: 490, english: "Smartphone", spanish: "Teléfono inteligente" },
    { id: 491, english: "Internet", spanish: "Internet" },
    { id: 492, english: "Wi-Fi", spanish: "Wi-Fi" },
    { id: 493, english: "Password", spanish: "Contraseña" },
    { id: 494, english: "Email", spanish: "Correo electrónico" },
    { id: 495, english: "Website", spanish: "Sitio web" },
    { id: 496, english: "App", spanish: "Aplicación" },
    { id: 497, english: "Keyboard", spanish: "Teclado" },
    { id: 498, english: "Mouse", spanish: "Ratón" },
    { id: 499, english: "Screen", spanish: "Pantalla" },
    { id: 500, english: "Printer", spanish: "Impresora" },
    { id: 501, english: "USB drive", spanish: "Memoria USB" },
    { id: 502, english: "Cable", spanish: "Cable" },
    { id: 503, english: "Charger", spanish: "Cargador" },
    { id: 504, english: "Headphones", spanish: "Auriculares" },
    { id: 505, english: "Speaker", spanish: "Altavoz" },
    { id: 506, english: "Microphone", spanish: "Micrófono" },
    { id: 507, english: "Camera", spanish: "Cámara" },
    { id: 508, english: "Television", spanish: "Televisión" },
    { id: 509, english: "Remote control", spanish: "Control remoto" },
    { id: 510, english: "Electricity", spanish: "Electricidad" },
    { id: 511, english: "Battery", spanish: "Batería" },
    { id: 512, english: "Robot", spanish: "Robot" },
    { id: 513, english: "Drone", spanish: "Dron" },
    {
      id: 514,
      english: "Artificial intelligence",
      spanish: "Inteligencia artificial",
    },
    { id: 515, english: "Virtual reality", spanish: "Realidad virtual" },
    { id: 516, english: "Social media", spanish: "Redes sociales" },
    { id: 517, english: "Cloud", spanish: "Nube" },
    { id: 518, english: "Download", spanish: "Descargar" },
    { id: 519, english: "Upload", spanish: "Subir" },
    { id: 520, english: "Search engine", spanish: "Motor de búsqueda" },
    { id: 521, english: "Data", spanish: "Datos" },
    { id: 522, english: "File", spanish: "Archivo" },
    { id: 523, english: "Folder", spanish: "Carpeta" },
    { id: 524, english: "Algorithm", spanish: "Algoritmo" },
    { id: 525, english: "Network", spanish: "Red" },
  ],

  "Common Verbs": [
    { id: 526, english: "To arrive", spanish: "Llegar" },
    { id: 527, english: "To leave", spanish: "Salir" },
    { id: 528, english: "To stay", spanish: "Quedarse" },
    { id: 529, english: "To begin", spanish: "Comenzar" },
    { id: 530, english: "To finish", spanish: "Terminar" },
    { id: 531, english: "To change", spanish: "Cambiar" },
    { id: 532, english: "To choose", spanish: "Elegir" },
    { id: 533, english: "To ask (a question)", spanish: "Preguntar" },
    { id: 534, english: "To answer", spanish: "Responder" },
    { id: 535, english: "To feel", spanish: "Sentir" },
    { id: 536, english: "To need", spanish: "Necesitar" },
    { id: 537, english: "To try (attempt)", spanish: "Intentar" },
    { id: 538, english: "To try (taste)", spanish: "Probar" },
    { id: 539, english: "To hope", spanish: "Esperar" },
    { id: 540, english: "To believe", spanish: "Creer" },
    { id: 541, english: "To forget", spanish: "Olvidar" },
    { id: 542, english: "To remember", spanish: "Recordar" },
    { id: 543, english: "To win", spanish: "Ganar" },
    { id: 544, english: "To lose", spanish: "Perder" },
    { id: 545, english: "To build", spanish: "Construir" },
    { id: 546, english: "To break", spanish: "Romper" },
    { id: 547, english: "To fix", spanish: "Arreglar" },
    { id: 548, english: "To wash", spanish: "Lavar" },
    { id: 549, english: "To clean", spanish: "Limpiar" },
    { id: 550, english: "To cook", spanish: "Cocinar" },
    { id: 551, english: "To dance", spanish: "Bailar" },
    { id: 552, english: "To sing", spanish: "Cantar" },
    { id: 553, english: "To paint", spanish: "Pintar" },
    { id: 554, english: "To draw", spanish: "Dibujar" },
    { id: 555, english: "To plan", spanish: "Planear" },
    { id: 556, english: "To organize", spanish: "Organizar" },
    { id: 557, english: "To decide", spanish: "Decidir" },
    { id: 558, english: "To borrow", spanish: "Pedir prestado" },
    { id: 559, english: "To lend", spanish: "Prestar" },
    { id: 560, english: "To celebrate", spanish: "Celebrar" },
    { id: 561, english: "To cry", spanish: "Llorar" },
    { id: 562, english: "To laugh", spanish: "Reír" },
    { id: 563, english: "To smile", spanish: "Sonreír" },
    { id: 564, english: "To relax", spanish: "Relajarse" },
    { id: 565, english: "To grow", spanish: "Crecer" },
    { id: 566, english: "To move (an object)", spanish: "Mover" },
    { id: 567, english: "To rest", spanish: "Descansar" },
    { id: 568, english: "To travel", spanish: "Viajar" },
    { id: 569, english: "To share", spanish: "Compartir" },
    { id: 570, english: "To discover", spanish: "Descubrir" },
    { id: 571, english: "To save (money)", spanish: "Ahorrar" },
    { id: 572, english: "To spend (money)", spanish: "Gastar" },
    { id: 573, english: "To push", spanish: "Empujar" },
    { id: 574, english: "To pull", spanish: "Halar" },
    { id: 575, english: "To climb", spanish: "Escalar" },
    { id: 576, english: "To jump", spanish: "Saltar" },
    { id: 577, english: "To throw", spanish: "Lanzar" },
    { id: 578, english: "To catch", spanish: "Atrapar" },
    { id: 579, english: "To sit", spanish: "Sentarse" },
    { id: 580, english: "To stand", spanish: "Pararse" },
    { id: 581, english: "To lie down", spanish: "Acostarse" },
    { id: 582, english: "To turn on", spanish: "Encender" },
    { id: 583, english: "To turn off", spanish: "Apagar" },
    { id: 584, english: "To break down (machine)", spanish: "Averiarse" },
    { id: 585, english: "To repair", spanish: "Reparar" },
    { id: 586, english: "To swim", spanish: "Nadar" },
    { id: 587, english: "To fish", spanish: "Pescar" },
    { id: 588, english: "To hunt", spanish: "Cazar" },
    { id: 589, english: "To bite", spanish: "Morder" },
    { id: 590, english: "To chew", spanish: "Masticar" },
    { id: 591, english: "To scream", spanish: "Gritar" },
    { id: 592, english: "To whisper", spanish: "Susurrar" },
    { id: 593, english: "To hug", spanish: "Abrazar" },
    { id: 594, english: "To kiss", spanish: "Besar" },
    { id: 595, english: "To meet", spanish: "Reunirse" },
    { id: 596, english: "To greet", spanish: "Saludar" },
    { id: 597, english: "To depart", spanish: "Partir" },
    { id: 598, english: "To arrive", spanish: "Llegar" },
    { id: 599, english: "To fear", spanish: "Temer" },
    { id: 600, english: "To trust", spanish: "Confiar" },
    { id: 601, english: "To doubt", spanish: "Dudar" },
    { id: 602, english: "To complain", spanish: "Quejarse" },
    { id: 603, english: "To promise", spanish: "Prometer" },
    { id: 604, english: "To apologize", spanish: "Disculparse" },
    { id: 605, english: "To forgive", spanish: "Perdonar" },
    { id: 606, english: "To pray", spanish: "Rezar" },
    { id: 607, english: "To win", spanish: "Ganar" },
    { id: 608, english: "To lose", spanish: "Perder" },
    { id: 609, english: "To tie (a game)", spanish: "Empatar" },
    { id: 610, english: "To bet", spanish: "Apostar" },
    { id: 611, english: "To perform", spanish: "Actuar" },
    { id: 612, english: "To entertain", spanish: "Entretener" },
    { id: 613, english: "To compete", spanish: "Competir" },
    { id: 614, english: "To watch", spanish: "Observar" },
    { id: 615, english: "To chase", spanish: "Perseguir" },
    { id: 616, english: "To explain", spanish: "Explicar" },
    { id: 617, english: "To translate", spanish: "Traducir" },
    { id: 618, english: "To imitate", spanish: "Imitar" },
    { id: 619, english: "To improve", spanish: "Mejorar" },
    { id: 620, english: "To worsen", spanish: "Empeorar" },
    { id: 621, english: "To measure", spanish: "Medir" },
    { id: 622, english: "To weigh", spanish: "Pesar" },
    { id: 623, english: "To calculate", spanish: "Calcular" },
    { id: 624, english: "To solve", spanish: "Resolver" },
    { id: 625, english: "To invent", spanish: "Inventar" },
    { id: 626, english: "To research", spanish: "Investigar" },
    { id: 627, english: "To study", spanish: "Estudiar" },
    { id: 628, english: "To teach", spanish: "Enseñar" },
    { id: 629, english: "To learn", spanish: "Aprender" },
    { id: 630, english: "To observe", spanish: "Observar" },
    { id: 631, english: "To analyze", spanish: "Analizar" },
    { id: 632, english: "To memorize", spanish: "Memorizar" },
    { id: 633, english: "To read aloud", spanish: "Leer en voz alta" },
    { id: 634, english: "To summarize", spanish: "Resumir" },
    { id: 635, english: "To demonstrate", spanish: "Demostrar" },
    { id: 636, english: "To prove", spanish: "Probar" },
    { id: 637, english: "To train", spanish: "Entrenar" },
    { id: 638, english: "To compete", spanish: "Competir" },
    { id: 639, english: "To win", spanish: "Ganar" },
    { id: 640, english: "To lose", spanish: "Perder" },
    { id: 641, english: "To adapt", spanish: "Adaptar" },
    { id: 642, english: "To adopt", spanish: "Adoptar" },
    { id: 643, english: "To adjust", spanish: "Ajustar" },
    { id: 644, english: "To mix", spanish: "Mezclar" },
    { id: 645, english: "To combine", spanish: "Combinar" },
    { id: 646, english: "To separate", spanish: "Separar" },
    { id: 647, english: "To select", spanish: "Seleccionar" },
    { id: 648, english: "To replace", spanish: "Reemplazar" },
    { id: 649, english: "To confirm", spanish: "Confirmar" },
    { id: 650, english: "To cancel", spanish: "Cancelar" },
    { id: 651, english: "To schedule", spanish: "Programar" },
    { id: 652, english: "To post (online)", spanish: "Publicar" },
    { id: 653, english: "To share (online)", spanish: "Compartir" },
    { id: 654, english: "To download", spanish: "Descargar" },
    { id: 655, english: "To upload", spanish: "Subir" },
    { id: 656, english: "To stream", spanish: "Transmitir" },
    { id: 657, english: "To interact", spanish: "Interactuar" },
    { id: 658, english: "To connect", spanish: "Conectar" },
    { id: 659, english: "To disconnect", spanish: "Desconectar" },
    { id: 660, english: "To print", spanish: "Imprimir" },
    { id: 661, english: "To scan", spanish: "Escanear" },
    { id: 662, english: "To customize", spanish: "Personalizar" },
    { id: 663, english: "To edit", spanish: "Editar" },
    { id: 664, english: "To broadcast", spanish: "Transmitir" },
    { id: 665, english: "To develop", spanish: "Desarrollar" },
    { id: 666, english: "To calculate", spanish: "Calcular" },
    { id: 667, english: "To invest", spanish: "Invertir" },
    { id: 668, english: "To trade", spanish: "Comerciar" },
    { id: 669, english: "To evaluate", spanish: "Evaluar" },
    { id: 670, english: "To construct", spanish: "Construir" },
    { id: 671, english: "To renovate", spanish: "Renovar" },
    { id: 672, english: "To protect", spanish: "Proteger" },
    { id: 673, english: "To support", spanish: "Apoyar" },
    { id: 674, english: "To criticize", spanish: "Criticar" },
    { id: 675, english: "To review", spanish: "Revisar" },
    { id: 676, english: "To research", spanish: "Investigar" },
    { id: 677, english: "To explore", spanish: "Explorar" },
    { id: 678, english: "To climb", spanish: "Trepar" },
    { id: 679, english: "To dive", spanish: "Bucear" },
    { id: 680, english: "To hike", spanish: "Caminar por el sendero" },
    { id: 681, english: "To travel", spanish: "Viajar" },
    { id: 682, english: "To commute", spanish: "Desplazarse" },
    { id: 683, english: "To exchange", spanish: "Intercambiar" },
    { id: 684, english: "To negotiate", spanish: "Negociar" },
    { id: 685, english: "To lead", spanish: "Liderar" },
    { id: 686, english: "To follow", spanish: "Seguir" },
    { id: 687, english: "To represent", spanish: "Representar" },
    { id: 688, english: "To organize", spanish: "Organizar" },
    { id: 689, english: "To govern", spanish: "Gobernar" },
    { id: 690, english: "To vote", spanish: "Votar" },
    { id: 691, english: "To protest", spanish: "Protestar" },
    { id: 692, english: "To manage", spanish: "Gestionar" },
    { id: 693, english: "To program", spanish: "Programar" },
    { id: 694, english: "To debug", spanish: "Depurar" },
    { id: 695, english: "To test", spanish: "Probar" },
    { id: 696, english: "To compile", spanish: "Compilar" },
    { id: 697, english: "To download", spanish: "Descargar" },
    { id: 698, english: "To install", spanish: "Instalar" },
    { id: 699, english: "To encrypt", spanish: "Encriptar" },
    { id: 700, english: "To decrypt", spanish: "Desencriptar" },
    { id: 701, english: "To sign", spanish: "Firmar" },
    { id: 702, english: "To register", spanish: "Registrar" },
    { id: 703, english: "To log in", spanish: "Iniciar sesión" },
    { id: 704, english: "To log out", spanish: "Cerrar sesión" },
    { id: 705, english: "To update", spanish: "Actualizar" },
    { id: 706, english: "To upgrade", spanish: "Mejorar" },
    { id: 707, english: "To back up", spanish: "Hacer una copia de seguridad" },
    { id: 708, english: "To recover", spanish: "Recuperar" },
    { id: 709, english: "To delete", spanish: "Borrar" },
    { id: 710, english: "To save", spanish: "Guardar" },
  ],
};
